### ISSUE TITLE
kdeconnect-send-file don't work

### ISSUE THREAD

**Issue by Sholum1** [carldotac/kdeconnect.el#3]
When I run the command "kdeconnect-send-file" and select the file a confirmation message "Shared" appears, however, the file is not sent to my phone.
I tried to run kdeconnect-cli -d "device id" --share path/to/file on Eshell and it worked perfectly, any tips?
Thanks in advance!!

Note: I use gccemacs

**Comment by carldotac** [comment]
Thanks for the report.

Is there a tilde (`~`) in the file path? It looks like wrapping the file name in quotes disables tilde expansion of the home directory. The `Shared` that you see is actually incomplete. Normally, it would also tell you the file it shared. Because it's trying to share a non-existent file, it looks like the file doesn't get listed, and your phone gets a notification that it has received a file that doesn't actually exist.

https://askubuntu.com/questions/1192981/why-isnt-tilde-recognised-as-home-folder-in-this-case

An immediate workaround is to ensure that you don't have a tilde in the file name, e.g. I should select the file `/home/carl/Downloads/example.png` instead of `~/Downloads/example.png`.

As for an actual fix, it looks like expand-file-name will parse `~/` into the actual home directory, so wrapping around the `path` calls should fix the issue. I should do some more due diligence that this is the right solution, but it's working for me in the scratch buffer.

https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Name-Expansion.html

After I check that this is indeed the right solution, I'll write the patch and close this issue. If you've installed through MELPA, I think they scan for changes pretty regularly. I'll try to get to this in the next week.

**Comment by Sholum1** [comment]
Yes, there was a (`~`) in the file path, thanks for the reply hahahah.

**Comment by carldotac** [comment]
Update pushed to master. MELPA should pick it up within a day.
