### ISSUE TITLE
wrong type arguement, array p, nil

### ISSUE THREAD

**Issue by muralikodali** [carldotac/kdeconnect.el#6]
i have recently upgraded emacs 28.1 

i am getting the following error.

```
wrong type argument, array p, nil
```

**Comment by carldotac** [comment]
Thanks for your report. I cannot replicate on my Emacs 28.1 on openSUSE Tumbleweed.

Have you set a value for kdeconnect-active-device, or can you check the value of that variable? (M-x helpful-variable kdeconnect-active-device). If this isn't set, that error will be thrown by Emacs. If you have successfully set that variable, please confirm that you can successfully invoke kdeconnect-cli from the command line, e.g., `kdeconnect-cli -d deviceid --ping` since this package is mostly string management to pass those arguments to the shell. If the above all works, please let me know your operating system, but I'm hopeful it's just a configuration issue rather than a bug introduced by a new version of Emacs.

**Comment by muralikodali** [comment]
My OS is Arch Linux.

my emacs configuration for kdecconnect.el is given below : 

```lisp
(use-package kdeconnect
  :straight t
  :custom
  (setq kdeconnect-devices "32afe912eef751fc,f6154b81da328c1d")
  (setq kdeconnect-active-device "32afe912eef751fc"))
```
`kdeconnect-cli -d  32afe912eef751fc --ping` is working as expected.

**Comment by carldotac** [comment]
Did my best to replicate your environment in a Manjaro KDE live image, including straight (never used before) and use-package (used to use). Try changing :custom to :config and I think your problem will be fixed--at least in the environment I set up, kdeconnect-devices and kdeconnect-active device weren't being set when declared using :custom. If that doesn't work, you can try to see where the issue is with the Emacs debugger or even just running the relevant Emacs Lisp. The kdeconnect-ping function is super simple, as long as the active device is correctly set there's really not much room for the function to break (kdeconnect-cli could still fail, like if the device were unreachable, but this isn't the error you're getting, and such an error would be printed by Emacs anyway).

```
;;;###autoload
(defun kdeconnect-ping ()
  "Ping the active device."
  (interactive)
  (shell-command
   (mapconcat 'identity
              (list "kdeconnect-cli" "-d"
                    (shell-quote-argument kdeconnect-active-device)
                    "--ping") " ")))
```

**Comment by muralikodali** [comment]
changing :custom to :config solved the problem.

Thanks for your advice.
